/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab9p2_heydenaldana_22111098;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author heyde
 */
public class jfMain extends javax.swing.JFrame {

    /**
     * Creates new form jfemployee
     */
    public jfMain() {
        initComponents();
        updateTable();
    }

    
    Connection conexion;
    PreparedStatement pst;
    ResultSet rs;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tpassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tphone = new javax.swing.JTextField();
        tsalary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtemp = new javax.swing.JTable();
        bempc = new javax.swing.JButton();
        bempe = new javax.swing.JButton();
        bempel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL - EMPLOYEE REGISTRATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        tname.setBackground(new java.awt.Color(255, 255, 255));
        tname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tname.setForeground(new java.awt.Color(51, 51, 51));
        tname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), null, null));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre:");

        tpassword.setBackground(new java.awt.Color(255, 255, 255));
        tpassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tpassword.setForeground(new java.awt.Color(51, 51, 51));
        tpassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), null, null));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Contraseña");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Telefono");

        tphone.setBackground(new java.awt.Color(255, 255, 255));
        tphone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tphone.setForeground(new java.awt.Color(51, 51, 51));
        tphone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), null, null));

        tsalary.setBackground(new java.awt.Color(255, 255, 255));
        tsalary.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tsalary.setForeground(new java.awt.Color(51, 51, 51));
        tsalary.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), null, null));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Salario");

        jtemp.setBackground(new java.awt.Color(204, 204, 204));
        jtemp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtemp.setForeground(new java.awt.Color(51, 51, 51));
        jtemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID:", "Nombre", "Contraseña", "Telefono", "Salario:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtempMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtemp);

        bempc.setBackground(new java.awt.Color(153, 153, 153));
        bempc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bempc.setForeground(new java.awt.Color(0, 0, 0));
        bempc.setText("Agregar empleado");
        bempc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bempcMouseClicked(evt);
            }
        });

        bempe.setBackground(new java.awt.Color(153, 153, 153));
        bempe.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bempe.setForeground(new java.awt.Color(0, 0, 0));
        bempe.setText("Editar empleado");
        bempe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bempeMouseClicked(evt);
            }
        });

        bempel.setBackground(new java.awt.Color(153, 153, 153));
        bempel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bempel.setForeground(new java.awt.Color(0, 0, 0));
        bempel.setText("Eliminar empleado");
        bempel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bempelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bempc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bempe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bempel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tphone, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addComponent(bempc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bempe, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bempel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bempcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bempcMouseClicked
        // TODO add your handling code here:
        String name, password, phone, salary;
        name = tname.getText();
        password = tpassword.getText();
        phone = tphone.getText();
        salary = tsalary.getText();
        
        int iphone = Integer.parseInt(phone);
        double dsalary = Double.valueOf(salary);
        
        try 
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            conexion = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\heyde\\Documents\\dbemployee.accdb");
            
            pst = conexion.prepareStatement("insert into employees (Nombre,Contraseña,Telefono,Salario) values (?,?,?,?)");
            pst.setString(1, name);
            pst.setString(2, password);
            pst.setInt(3, iphone);
            pst.setDouble(4, dsalary);
            
            pst.executeUpdate();
            updateTable();
            
            JOptionPane.showMessageDialog(this, "Registro Agregado");
            
            tname.setText("");
            tpassword.setText("");
            tphone.setText("");
            tsalary.setText("");
            tname.requestFocus();
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        
        
    }//GEN-LAST:event_bempcMouseClicked

    private void jtempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtempMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dft = (DefaultTableModel)jtemp.getModel();
        int selectedIndex = jtemp.getSelectedRow();
        
        int ID = Integer.parseInt(dft.getValueAt(selectedIndex, 0).toString());
        tname.setText(dft.getValueAt(selectedIndex, 1).toString());
        tpassword.setText(dft.getValueAt(selectedIndex, 2).toString());
        tphone.setText(dft.getValueAt(selectedIndex, 3).toString());
        tsalary.setText(dft.getValueAt(selectedIndex, 4).toString());
        
        
    }//GEN-LAST:event_jtempMouseClicked

    private void bempeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bempeMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dft = (DefaultTableModel)jtemp.getModel();
        int selectedIndex = jtemp.getSelectedRow();
        
        String name, password, phone, salary;
        name = tname.getText();
        password = tpassword.getText();
        phone = tphone.getText();
        salary = tsalary.getText();
        
        int iphone = Integer.parseInt(phone);
        int ID = Integer.parseInt(dft.getValueAt(selectedIndex, 0).toString());
        
        double dsalary = Double.valueOf(salary);
        
        try 
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            conexion = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\heyde\\Documents\\dbemployee.accdb");
            
            pst = conexion.prepareStatement("update employees set Nombre=?, Contraseña=?, Telefono=?, Salario=? where ID=? ");
            pst.setString(1, name);
            pst.setString(2, password);
            pst.setInt(3, iphone);
            pst.setDouble(4, dsalary);
            pst.setInt(5, ID);
            pst.executeUpdate();
            updateTable();
            
            JOptionPane.showMessageDialog(this, "Registro Modificado");
            
            tname.setText("");
            tpassword.setText("");
            tphone.setText("");
            tsalary.setText("");
            tname.requestFocus();
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } 
    }//GEN-LAST:event_bempeMouseClicked

    private void bempelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bempelMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dft = (DefaultTableModel)jtemp.getModel();
        int selectedIndex = jtemp.getSelectedRow();
        int ID = 0;
        ID = Integer.parseInt(dft.getValueAt(selectedIndex, 0).toString());

        if(ID == 0)
        {
            JOptionPane.showMessageDialog(this, "DEBE ELEGIR UN REGISTRO DE LA TABLA");
            return;
        }
        int dresult = JOptionPane.showConfirmDialog(null, "¿Estas seguro que quieres eliminar este registro?\n\nNO SE PUEDE DESHACER ESTA ACCION.");
        
        if(dresult == JOptionPane.YES_NO_OPTION)
        {
            try 
            {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                conexion = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\heyde\\Documents\\dbemployee.accdb");

                pst = conexion.prepareStatement("delete from employees where ID=? ");

                pst.setInt(1, ID);
                pst.executeUpdate();
                updateTable();

                JOptionPane.showMessageDialog(this, "Registro Eliminado");

                tname.setText("");
                tpassword.setText("");
                tphone.setText("");
                tsalary.setText("");
                tname.requestFocus();

            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            } 
        }
    }//GEN-LAST:event_bempelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMain().setVisible(true);
            }
        });
    }

    public void updateTable()
    {
        try 
        {
            int c;
            
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            conexion = DriverManager.getConnection("jdbc:ucanaccess://./JamesApp.accdb");
            
            pst = conexion.prepareStatement("select * from employees");
            rs = pst.executeQuery();
            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            
            DefaultTableModel dft = (DefaultTableModel)jtemp.getModel();
            dft.setRowCount(0);
            while(rs.next())
            {
                Vector v2 = new Vector();
                for (int i = 0; i <= c; i++) 
                {
                    v2.add(rs.getInt("ID"));
                    v2.add(rs.getString("Nombre"));
                    v2.add(rs.getString("Contraseña"));
                    v2.add(rs.getInt("Telefono"));
                    v2.add(rs.getDouble("Salario"));
                }
                dft.addRow(v2);
            }
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bempc;
    private javax.swing.JButton bempe;
    private javax.swing.JButton bempel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtemp;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tpassword;
    private javax.swing.JTextField tphone;
    private javax.swing.JTextField tsalary;
    // End of variables declaration//GEN-END:variables
}
